# Declare characters used by this game.
define s = Character('Stella', color="#518CFF")
define p = Character('Pucas', color="#F2E1AE")
define star = Character('Starbuck', color="#00704a")
define m = Character('Maddie', color="#FF0066")
define k = Character('Keith', color="#B35900")
define shrimp = Character('Darmascula', color="#FFC0CB")
define tiger = Character('Tiger Mammal', color="#AA1111")
define babytiger = Character('Baby Tiger', color="#2233FF")
define nimo = Character('Nimo', color="#AAAAAA")
define airhorn = Character('Airhorn',color="#FFFF00")
define Mom = Character('Mom' ,color="#00ff00")
define Joseph = Character('Joseph' ,color="#FF0000")
define jacques = Character('Jàçqüés' ,color="#ABCDEF")
define zach = Character('Zach', color="#BBAAff")
define saki = Character('SakiSaki-chan', color="#ff66ff")
define Prof = Character('Professor Fukklesprout', color="#ccff66")
define Frito = Character('Frito Cubby', color="#ccaadd")
define cdog = Character('C-Dawg', color = "#f79744")
define durks = Character('The Durks', color = "#42b879") 
define gdubs = Character('G-Dubs', color = "#d1d1e0")
define stormee = Character('Stormee', color = "#cc99ff")
define mat = Character('MatTt', color = "#bbff33")
define chi = Character('Chi', color = "#ffb84d")
define connie = Character('Connie', color = "#993300")
define lassi = Character('Lassi', color = "#ffcc66")
define girl = Character('Girl', color = "#FFFFFF")

define tiger_manager = Character('Tiger Manley, Innovative Fiduciary', color="#0066ff")
return 
