#Start BG
image bg black = "#000000"
image bg white = "#FFFFFF"
image bg gym far = "gym_far.jpg"
image bg gym close = "gym_close.jpg"
image bg love basic = "love_basic.jpg"
image bg past playground = "past_playground.jpg"
image bg past woodchips = "past_woodchips.jpg"
image bg mystic swirl = "mystic_swirl.jpg"
image bg parking lot = "parking_lot.jpg"
image bg parking storefront = "parking_storefront.jpg"
image bg greenroom = "greenroom.jpg"
image bg school front = "school_front.jpg"
image bg speech giving = "speech_giving.jpg"
image bg speech finish = "speech_finish.jpg"
#Alpha Phi BG
image bg quad_busy = "quad_busy.jpg"
image bg quad_closeup = "quad_closeup.jpg"
image bg dorm_room = "dorm_room.jpg"
image bg stairwell = "stairwell.jpg"
image bg airport = "airport.jpg"
image bg srat = "srat.jpg"
image bg aphi_enter = "aphi_enter.jpg"
image bg basement = "basement.jpg"
image bg pool = "pool.jpg"
image bg library = "library.jpg"
#Pucas BG
image bg cabin_exterior = "cabin_exterior.jpg"
image bg cabin_front = "cabin_front.jpg"
image bg cabin_upstairs = "cabin_upstairs.jpg"
image bg fireplace = "fireplace.jpg"
image bg forestheart = "forestheart.jpg"
image bg snowy_road = "snowy_road.jpg"
image bg nightwoods = "woods.jpg"
image bg deepwoods = "deepwoods.jpg"
image bg deeperwoods = "deeperwoods.jpg"
image bg coldforest = "cold_forest.jpg"
#Storgan BG
image bg boardroom = "boardroom.jpg"
image bg storgan front = "storgan_front.jpg"