label pucasCh1: 
    $ sexy_factor = 100

    show bg black
    centered "Winter"
    centered "1.5 years later"
    show bg snowy_road
    with dissolve
    "It's cold."
    "Even in the car, the cold seeps through the thin window panes."
    "Our breath is frozen onto the inside of the glass, a web of crystal."
    "I let out a little shiver."
    jacques "You're cold? We're close to my cabin."
    "Jàçqüés turns to me, and nods reassuringly."
    "I've known Jàçqüés for years."
    "Our dads used to work together, so we ran in to each other at work functions often."
    "Now, he's going to school in California."
    "He takes one of his tiny hands off the steering wheel, and points to his shirt."
    "It's a cute little walrus face."
    jacques "Good thing my spirit animal is a walrus. Otherwise I'd be freezing too!"
    "He turns back to the road, concentrating on the crunchy, snowy road."
    prof "Jàçqüés, I'm tired desu."
    jacques "Stop."
    jacques "Whining."
    jacques "Dirty weaboo."
    prof "Grrrrr."
    "From the back seat, Professor Fukklesprout grumbles."
    "He's lanky, with long, brown hair that hangs in his face like an anime character."
    "After spending time in Japan, he developed some strange psychological disorder, where he thought he was still in Japan."
    "When I first met him, he'd only speak Japanese."
    "Slowly, over the last few years, he's come out of his shell and used English again."
    frito "Yeah Fukklesprout, cut it out, you little bitch."
    "Frito Cubby glares at him over top her glasses."
    "I never went to school with Frito. She went to the school across town."
    "She's always felt a little enigmatic to me, like somehow, I'm her competition."
    "But, she's so much fun to have around, so it's not a big deal."
    "She pulls a small takeout box out of her coat pocket."
    frito "Have some of this, it'll warm you up."
    "Fukklesprout peers around the box curiously."
    prof "This kind of looks like a box I had in Japan once. When I opened it up, a bunch of really kawaii neko popped out from the box and gave me an allergy attack. What's in here?"
    zach "Just open it."
    "Zach Peterson."
    "What a guy."
    "He was in many of my classes in high school."
    "An expert cartographer, statistician, and master of wit, Zach was one of my most valuable assets in high school."
    "He's also quite the catch."
    "His red hair flows in elegant dreads, like an Irish reggae band's frontman."
    zach "Come on. What's the worst it could be?"
    "Fukklesprout sighs."
    "He pops the lid on the box."
    prof "Aaagggghhhh!!!!"
    frito "Hahahaha, suck it, nerd."
    zach "Nice going dude."
    "I peer over the edge of the box."
    "Inside is a big chunk of falafel."
    prof "GET THIS GARBAGE AWAY FROM ME!"
    "He quickly rolls down the window, letting in a rush of cold air."
    prof "BEGONE FOUL SUBSTANCE!"
    "He hucks the box with his full strength."
    "It lands with a-"
    "*poof*"
    "-before sinking into the twilit snow."
    frito "Hey, come on man, that was my dinner!"
    prof "You all KNOW how much I hate non-Japanese food!"
    "Jàçqüés rolls his eyes. He must be used to this."
    "I giggle. What a classic group of friends."
    show bg cabin_exterior
    with fade

    return
